# Generated by Django 4.0.4 on 2022-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='candprofiles')),
                ('resume', models.FileField(null=True, upload_to='cvs')),
                ('qualification', models.CharField(max_length=120)),
                ('skills', models.CharField(max_length=120)),
                ('experience', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
