# Generated by Django 4.0.4 on 2022-06-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_applications'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applications',
            unique_together={('applicant', 'job')},
        ),
    ]
