# Generated by Django 4.0.4 on 2022-06-04 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0005_alter_companyprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='logo',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='services',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
