# Generated by Django 4.0.4 on 2022-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_remove_companyprofile_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(null=True, upload_to='companyprofile'),
        ),
    ]
